# Generated by Django 4.1.7 on 2023-07-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_regNo', models.TextField(unique=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_email', models.EmailField(max_length=200)),
                ('employee_mobile', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
